---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/cart.json":
    get:
      summary: show cart
      tags:
      - Cart
      responses:
        '200':
          description: Get cart content
          content:
            application/json:
              example:
                success: true
                id: 18
                token: 4b6d91fe-ccb2-4d15-820f-8d563dabc635
                items:
                - id: 34
                  name: Decred
                  price: '1.11'
                  quantity: 3
                - id: 35
                  name: Monero
                  price: '8.27'
                  quantity: 1
                total_price: '11.6'
        '401':
          description: Unauthorized
  "/cart/{cart_token}.json":
    get:
      summary: show cart
      tags:
      - Cart
      parameters:
      - in: path
        name: cart_token
        required: true
        description: Cart Token.
        schema:
          type: string
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Get cart content
          content:
            application/json:
              example:
                success: true
                id: 18
                token: 4b6d91fe-ccb2-4d15-820f-8d563dabc635
                items:
                - id: 34
                  name: Decred
                  price: '1.11'
                  quantity: 3
                - id: 35
                  name: Monero
                  price: '8.27'
                  quantity: 1
                total_price: '11.6'
  "/cart/item.json":
    post:
      summary: add product to cart
      tags:
      - Cart
      parameters: []
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Add product to cart
        '422':
          description: UnprocessableEntity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                  example: 1
                quantity:
                  type: integer
                  example: 10
    delete:
      summary: remove product from cart
      tags:
      - Cart
      parameters: []
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Remove product from cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                  example: 1
definitions:
  unauthorized_body:
    type: object
    properties:
      error:
        type: string
        example: You need to sign in or sign up before continuing.
